[mypy]
no_implicit_optional = True
disable_error_code = var-annotated
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# Dieser Abschnitt hat gefehlt:
[mypy.plugins.django-stubs]
django_settings_module = "qfieldcloud.settings"

[mypy-*.migrations.*]
ignore_errors = True

[mypy-*.tests.*]
ignore_errors = True
