[mypy]
# Global settings and plugins MUST go here
no_implicit_optional = True
disable_error_code = var-annotated
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# Section-specific settings go below
[mypy-*.migrations.*]
ignore_errors = True

[mypy-*.tests.*]
ignore_errors = True
